# Generated by Django 4.1.7 on 2024-05-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentcard', '0002_studentcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcard',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='studentcard',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
